version: "3.8"

services:
  postgres_mlflow:
    image: postgres:15
    container_name: postgres_mlflow
    restart: always
    environment:
      POSTGRES_USER: wrm
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - /home/wrm/pgdata:/var/lib/postgresql/data
    networks:
      - mlops_network

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: wrm
      MINIO_ROOT_PASSWORD: senha_segura
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - mlops_network

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - postgres_mlflow
      - minio
    volumes:
      - ./mlruns:/mlflow/mlruns   # Persistência dos runs
    command:
      - mlflow
      - server
      - --backend-store-uri
      - postgresql://wrm:senha_segura@postgres_mlflow:5432/mlflow_db
      - --default-artifact-root
      - s3://mba-mlops-bucket/
      - --host
      - 0.0.0.0
      - --port
      - "5000"
    networks:
      - mlops_network

  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: devcontainer_mba_mlops
    volumes:
      - ./:/workspace
    networks:
      - mlops_network
    command: sleep infinity

networks:
  mlops_network:
    driver: bridge
