version: "3.8"

services:
  postgres_mlflow:
    image: postgres:15
    container_name: postgres_mlflow
    restart: always
    environment:
      POSTGRES_USER: wrm
      POSTGRES_PASSWORD: senha_segura
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - /home/wrm/pgdata:/var/lib/postgresql/data
    networks:
      - mlops_network

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: wrm
      MINIO_ROOT_PASSWORD: senha_segura
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - mlops_network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow
    restart: always
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres_mlflow
      - minio
    networks:
      - mlops_network

networks:
  mlops_network:
    driver: bridge
