version: '3.9'

services:
  quantumfinance:
    build:
      context: ..
      dockerfile: container_solução/Dockerfile
    container_name: quantumfinance_app
    ports:
      - "8080:8000"   # API FastAPI
      - "8600:8501"   # Streamlit
    volumes:
      - ../src:/workspace/src
      - ../models:/workspace/models
    networks:
      - mba_mlops_mlops_network   # <<< rede unificada

networks:
  mba_mlops_mlops_network:
    external: true
