artifact_uri: file:///workspace/notebooks/mlruns/604912714123659266/e2316471a7174e69ae7b582d00f9e645/artifacts
end_time: null
entry_point_name: ''
experiment_id: '604912714123659266'
lifecycle_stage: active
run_id: e2316471a7174e69ae7b582d00f9e645
run_name: random_forest_gridsearch_v1.1_curated
source_name: ''
source_type: 4
source_version: ''
start_time: 1752615430491
status: 1
tags: []
user_id: root
